package com.yangqi.recommendedsystem.dal;

import com.yangqi.recommendedsystem.model.CategoryModel;

import java.util.List;

public interface CategoryModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Feb 23 20:24:55 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 查询所有品类
     *
     * @return 所有品类列表
     */
    List<CategoryModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Feb 23 20:24:55 CST 2020
     */
    int insert(CategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Feb 23 20:24:55 CST 2020
     */
    int insertSelective(CategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Feb 23 20:24:55 CST 2020
     */
    CategoryModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Feb 23 20:24:55 CST 2020
     */
    int updateByPrimaryKeySelective(CategoryModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbg.generated Sun Feb 23 20:24:55 CST 2020
     */
    int updateByPrimaryKey(CategoryModel record);

    /**
     * 查询所有的品类
     *
     * @return 品类数量
     */
    Integer countAllCategory();
}