package com.yangqi.recommendedsystem.dal;

import com.yangqi.recommendedsystem.model.ShopModel;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Feb 23 21:30:21 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 查询所有的商品
     *
     * @return 商品列表
     */
    List<ShopModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Feb 23 21:30:21 CST 2020
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Feb 23 21:30:21 CST 2020
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Feb 23 21:30:21 CST 2020
     */
    ShopModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Feb 23 21:30:21 CST 2020
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Sun Feb 23 21:30:21 CST 2020
     */
    int updateByPrimaryKey(ShopModel record);

    /**
     * 查询所有门店
     *
     * @return 门店数量
     */
    Integer countAllShop();

    /**
     * 推荐系统 1.0
     *
     * @param longitude 经度
     * @param latitude  维度
     * @return 推荐列表
     */
    List<ShopModel> recommend(@Param("longitude") BigDecimal longitude, @Param("latitude") BigDecimal latitude);

    /**
     * 搜索系统 1.0
     *
     * @param longitude  经度
     * @param latitude   维度
     * @param keyword    关键词
     * @param categoryId 分类
     * @param orderby    排序
     * @param tags       标签
     * @return 搜索列表
     */
    List<ShopModel> search(@Param("longitude") BigDecimal longitude, @Param("latitude") BigDecimal latitude,
                           @Param("keyword") String keyword, @Param("categoryId") Integer categoryId, @Param("orderby") Integer orderby,
                           @Param("tags") String tags);

    /**
     * 关键词、标签聚合
     *
     * @param keyword    关键词
     * @param categoryId 分类
     * @param tags       标签
     * @return 推荐列表
     */
    List<Map<String, Object>> searchGroupByTags(@Param("keyword") String keyword, @Param("categoryId") Integer categoryId,
                                                @Param("tags") String tags);

    /**
     * 重新关联索引
     *
     * @param sellerId 商家 ID
     * @param categoryId 分类 ID
     * @param shopId 商品 ID
     * @return 重建列表
     */
    List<Map<String, Object>> buildESQuery(@Param("sellerId") Integer sellerId, @Param("categoryId") Integer categoryId,
                                           @Param("shopId") Integer shopId);
}